import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
  structure
    - goals
    - activities
    - categories
    - activity entries

  todos
  - save and load (just use firebase)
  - stack rank of next activities to do
  - when delete activity, dispatch action to goal (whether to delete)
  - when edit activity (i.e. remove category), dispatch to categories
  - refactor to use 1 component for "enter new" and table
  - validation logic for submitting new *(activity/goal/entry)
  - filter selection for autocomplete when searching
  - categories tab maybe
  - integration w/ database (firebase free?)
  - nice single stacked bar visualization of how the session will turn out
    https://remixicon.com/ for priorities
  bugs
    - support for days, if u add past minute, it bugs out

  // possible queries
  // 1. how many times has an activity been done this month, week, day
  // to filter eligible activities to show
  // 2. calendar view of activities
  // 3. charts log view of activities fully filterable to track trends  
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <div className="flex flex-col items-start h-screen p-12 gap-4">
            {children}
          </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
